export const SELECTED_RECORDING = {'title': 'Record', 'artist': 'Test artist', 'isrc': "654443", 'duration': "433"}
export const RECORDING = {'title': 'Record', 'artist': 'Test artist', 'isrc': "654443", 'duration': "433"}
export const ELEMENTS = [{'title': 'Test record', 'artist': 'Test artist', 'isrc': "654443", 'duration': "433"}]
export const INPUT_RECORD_LIST = [{'title': 'Input record', 'artist': 'Test artist', 'isrc': "654443", 'duration': "433"}]
export const DB_RECORD_LIST = [{'title': 'DB record', 'artist': 'Test artist', 'isrc': "654443", 'duration': "433"}]
export const MATCH_RECORD_LIST = [{'title': 'Match record', 'artist': 'Test artist', 'isrc': "654443", 'duration': "433"}]
export const EMPTY_LIST = []
export const EMPTY_INPUT = ''
export const EMPTY_RECORDING = { 'title': '', 'artist': '', 'isrc': '', 'duration': '' }
export const INPUT_RECORD = {'title': 'Input record', 'artist': 'Test artist', 'isrc': "654443",  'duration': "433"}
export const DB_RECORD = {'title': 'DB record', 'artist': 'Test artist', 'isrc': "654443",  'duration': "433"}
export const ELEMENTS_MATCHED = [{'title': 'Test recording', 'artist': 'Test artist', 'isrc': "654443", 'duration': "433", 'matchedRecording':{'title': 'Matched recording', 'artist': 'Test artist', 'isrc': "654443", 'duration': "433"}}]
export const SEARCH_TEXT = "Search test"
